### ISSUE TITLE
개발 브랜치 생성 & 개발 환경 구축

### ISSUE THREAD

**Issue by regi93** [iOS-201create/iOS#1]
### ✅ Todo
- [ ] 개발 브랜치 생성
- [ ]  Kingfisher, Alamofire 세팅
- [ ] 타겟버전 설정 (iOS 15+)
